# Generated by Django 5.0.7 on 2025-02-26 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loging', '0002_alter_student_course_feepayment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='course',
        ),
        migrations.RemoveField(
            model_name='feepayment',
            name='application',
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='FeePayment',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
