# Generated by Django 5.2 on 2025-05-07 08:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loging', '0002_initial'),
        ('useraccess', '0003_alter_unit_created_by_alter_unit_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='googleformassignment',
            name='level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='useraccess.level'),
        ),
        migrations.AddField(
            model_name='notes',
            name='level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='useraccess.level'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='useraccess.level'),
        ),
        migrations.AddField(
            model_name='tutorial',
            name='level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='useraccess.level'),
        ),
    ]
