# Generated by Django 5.2 on 2025-05-07 08:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loging', '0003_googleformassignment_level_notes_level_quiz_level_and_more'),
        ('useraccess', '0003_alter_unit_created_by_alter_unit_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='googleformassignment',
            name='level',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='useraccess.level'),
            preserve_default=False,
        ),
    ]
