# Generated by Django 5.0.7 on 2025-02-28 20:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loging', '0004_initial'),
        ('useraccess', '0022_studentapp_total_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feestatement',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='useraccess.studentapp'),
        ),
    ]
