# Generated by Django 5.0.7 on 2025-03-01 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loging', '0005_alter_feestatement_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='feepayment',
            name='mode_of_payment',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='feepayment',
            name='receipt_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='feepayment',
            name='registration_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='FeeStatement',
        ),
    ]
