# Generated by Django 5.0.7 on 2025-03-03 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loging', '0006_feepayment_mode_of_payment_feepayment_receipt_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feepayment',
            name='remaining_balance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
