# Generated by Django 5.0.7 on 2025-03-03 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loging', '0007_feepayment_remaining_balance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feepayment',
            old_name='remaining_balance',
            new_name='new_remaining_balance',
        ),
    ]
