# Generated by Django 5.0.7 on 2025-03-04 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loging', '0008_rename_remaining_balance_feepayment_new_remaining_balance'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentBioData',
        ),
    ]
