# Generated by Django 5.0.7 on 2025-03-04 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loging', '0009_delete_studentbiodata'),
    ]

    operations = [
        migrations.AddField(
            model_name='feepayment',
            name='fees_payment_for',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
