# Generated by Django 5.0.7 on 2025-03-11 08:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loging', '0010_feepayment_fees_payment_for'),
        ('useraccess', '0024_customeruser_is_teacher_teacher'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleFormAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('link', models.URLField()),
                ('created_at', models.DateField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='useraccess.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='googleform', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
