# Generated by Django 5.1.7 on 2025-03-14 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loging', '0014_alter_quizattempt_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizattempt',
            name='registration_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
