# Generated by Django 5.1.7 on 2025-03-26 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loging', '0015_quizattempt_registration_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.PositiveIntegerField()),
                ('subject', models.CharField(blank=True, max_length=50, null=True)),
                ('message', models.TextField()),
                ('create_at', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
