# Generated by Django 5.1.7 on 2025-04-02 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loging', '0019_composeemail_forward_reply'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='subject',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
