# Generated by Django 5.1.7 on 2025-04-03 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loging', '0020_reply_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('start_month', models.CharField(blank=True, max_length=20, null=True)),
                ('end_month', models.CharField(blank=True, max_length=20, null=True)),
                ('start_year', models.IntegerField(blank=True, null=True)),
                ('end_year', models.IntegerField(blank=True, null=True)),
                ('start_day', models.IntegerField(blank=True, null=True)),
                ('end_day', models.IntegerField(blank=True, null=True)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('location', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ['start_date'],
            },
        ),
    ]
