# Generated by Django 5.1.7 on 2025-04-06 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loging', '0024_blog_alter_event_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='teacher',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
