# Generated by Django 5.1.7 on 2025-04-07 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loging', '0025_alter_quiz_teacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('image', models.ImageField(upload_to='slider_images/')),
                ('sub_title', models.CharField(blank=True, max_length=50, null=True)),
                ('content', models.TextField()),
                ('is_approved', models.BooleanField(default=False)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
