# Generated by Django 5.1.7 on 2025-04-09 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loging', '0026_slider'),
    ]

    operations = [
        migrations.AddField(
            model_name='feepayment',
            name='payment_phone_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
