# Generated by Django 5.1.7 on 2025-04-28 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loging', '0027_feepayment_payment_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='image',
            field=models.ImageField(default='Youth.jpg', upload_to='slider_images/'),
        ),
    ]
