# Generated by Django 5.1.7 on 2025-04-28 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loging', '0028_alter_slider_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteLogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo_name', models.CharField(default='My Website', max_length=100)),
                ('logo', models.ImageField(upload_to='logos/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
    ]
