# Generated by Django 5.2 on 2025-05-13 12:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccess', '0003_alter_unit_created_by_alter_unit_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimetableConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('lesson_duration_minutes', models.PositiveIntegerField(default=60)),
                ('learning_days', models.JSONField()),
                ('short_break_start', models.TimeField()),
                ('short_break_end', models.TimeField()),
                ('lunch_break_start', models.TimeField()),
                ('lunch_break_end', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lessons_per_week', models.PositiveIntegerField(default=2)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='useraccess.level')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='useraccess.teacher')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='useraccess.unit')),
            ],
        ),
        migrations.CreateModel(
            name='WeeklySlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=9)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='useraccess.lesson')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='useraccess.level')),
            ],
            options={
                'unique_together': {('level', 'day_of_week', 'start_time')},
            },
        ),
    ]
