# Generated by Django 5.2 on 2025-05-02 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('useraccess', '0003_remove_userprofile_course_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catscore',
            name='modified_at',
        ),
    ]
