# Generated by Django 5.0.7 on 2025-02-06 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('useraccess', '0003_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='date_of_birth',
        ),
    ]
