# Generated by Django 5.2 on 2025-05-02 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccess', '0004_remove_catscore_modified_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='cat',
            name='attendance_sheet',
            field=models.FileField(blank=True, null=True, upload_to='test_attendance/cats/'),
        ),
        migrations.AddField(
            model_name='cat',
            name='mark_sheet',
            field=models.FileField(blank=True, null=True, upload_to='marksheets/cats/'),
        ),
        migrations.AddField(
            model_name='cat',
            name='pc_waiting',
            field=models.FileField(blank=True, null=True, upload_to='pc_waiting/cats/'),
        ),
    ]
