# Generated by Django 5.2 on 2025-05-13 19:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccess', '0004_timetableconfig_lesson_weeklyslot'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeetingTime',
            fields=[
                ('pid', models.AutoField(primary_key=True, serialize=False)),
                ('time', models.CharField(choices=[('9:30 - 10:30', '9:30 - 10:30'), ('10:30 - 11:30', '10:30 - 11:30'), ('11:30 - 12:30', '11:30 - 12:30'), ('12:30 - 1:30', '12:30 - 1:30'), ('2:30 - 3:30', '2:30 - 3:30'), ('3:30 - 4:30', '3:30 - 4:30'), ('4:30 - 5:30', '4:30 - 5:30')], max_length=20)),
                ('day', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday')], max_length=10)),
            ],
            options={
                'unique_together': {('time', 'day')},
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('r_number', models.CharField(max_length=10, unique=True)),
                ('seating_capacity', models.PositiveIntegerField(default=30)),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='useraccess.teacher')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='useraccess.level')),
                ('meeting_time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='useraccess.meetingtime')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='useraccess.room')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='useraccess.unit')),
            ],
            options={
                'verbose_name': 'Session',
                'verbose_name_plural': 'Sessions',
                'unique_together': {('instructor', 'meeting_time'), ('level', 'meeting_time'), ('room', 'meeting_time')},
            },
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='level',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='teacher',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='unit',
        ),
        migrations.RemoveField(
            model_name='weeklyslot',
            name='lesson',
        ),
        migrations.DeleteModel(
            name='TimetableConfig',
        ),
        migrations.AlterUniqueTogether(
            name='weeklyslot',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='weeklyslot',
            name='level',
        ),
        migrations.DeleteModel(
            name='Lesson',
        ),
        migrations.DeleteModel(
            name='WeeklySlot',
        ),
    ]
