# Generated by Django 5.0.7 on 2025-02-21 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('useraccess', '0005_alter_student_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PasswordReset',
        ),
    ]
