# Generated by Django 5.2 on 2025-05-30 08:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccess', '0005_meetingtime_room_session_remove_lesson_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentapp',
            name='level',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='levels', to='useraccess.level'),
        ),
    ]
