# Generated by Django 5.2 on 2025-05-03 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccess', '0005_cat_attendance_sheet_cat_mark_sheet_cat_pc_waiting'),
    ]

    operations = [
        migrations.AddField(
            model_name='cat',
            name='created_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='cat',
            name='created_by',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
