# Generated by Django 5.2 on 2025-05-30 08:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccess', '0006_alter_studentapp_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentapp',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='levels', to='useraccess.level'),
        ),
    ]
