# Generated by Django 5.2 on 2025-05-30 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccess', '0007_alter_studentapp_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_levels', to='useraccess.course'),
        ),
    ]
