# Generated by Django 5.0.7 on 2025-02-26 13:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccess', '0008_department_alter_customeruser_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeruser',
            name='date_joined',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 2, 26, 13, 18, 34, 325849, tzinfo=datetime.timezone.utc), editable=False, null=True),
        ),
    ]
