# Generated by Django 5.0.7 on 2025-02-26 13:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccess', '0009_customeruser_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeruser',
            name='date_joined',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False, null=True),
        ),
    ]
