# Generated by Django 5.0.7 on 2025-02-26 19:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccess', '0010_alter_customeruser_date_joined'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentapplication',
            old_name='acc',
            new_name='user',
        ),
        migrations.AddField(
            model_name='course',
            name='created_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='period_of_study',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='price',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='department',
            name='created_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False, null=True),
        ),
    ]
