# Generated by Django 5.0.7 on 2025-02-27 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccess', '0012_alter_customeruser_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentapplication',
            name='is_approved',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
