# Generated by Django 5.0.7 on 2025-02-27 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccess', '0013_studentapplication_is_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentapplication',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
