# Generated by Django 5.0.7 on 2025-02-27 11:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccess', '0014_alter_studentapplication_is_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentapplication',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
