# Generated by Django 5.0.7 on 2025-02-27 11:43

import django.db.models.deletion
import useraccess.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccess', '0015_alter_studentapplication_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentapplication',
            name='user',
            field=models.OneToOneField(default=useraccess.models.default_user_instance, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
