# Generated by Django 5.0.7 on 2025-02-27 13:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccess', '0017_studentapp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentapp',
            name='stud',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
