# Generated by Django 5.0.7 on 2025-02-27 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccess', '0018_alter_studentapp_stud'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeruser',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='StudentApplication',
        ),
    ]
