# Generated by Django 5.0.7 on 2025-02-28 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccess', '0019_customeruser_is_active_delete_studentapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentapp',
            name='remaining_balance',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='studentapp',
            name='total_fees',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, editable=False, max_digits=10, null=True),
        ),
    ]
