# Generated by Django 5.0.7 on 2025-02-28 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccess', '0020_studentapp_remaining_balance_studentapp_total_fees'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentapp',
            name='remaining_balance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
