# Generated by Django 5.0.7 on 2025-02-28 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccess', '0021_alter_studentapp_remaining_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentapp',
            name='total_paid',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, editable=False, max_digits=10, null=True),
        ),
    ]
