# Generated by Django 5.1.7 on 2025-03-19 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccess', '0024_customeruser_is_teacher_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentapp',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
    ]
