# Generated by Django 5.1.7 on 2025-04-09 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccess', '0025_studentapp_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='is_tution',
            field=models.BooleanField(default=False),
        ),
    ]
