# Generated by Django 5.1.7 on 2025-04-09 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccess', '0026_department_is_tution'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='course-images'),
        ),
        migrations.AddField(
            model_name='department',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='department-images'),
        ),
    ]
