# Generated by Django 5.1.7 on 2025-04-09 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccess', '0027_course_image_department_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='image',
            field=models.ImageField(blank=True, default='Youth.jpg', null=True, upload_to='department-images'),
        ),
    ]
