# Generated by Django 5.2 on 2025-04-30 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccess', '0029_unit_practical_cat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='unit_code',
            field=models.CharField(blank=True, editable=False, max_length=15, null=True, unique=True),
        ),
    ]
