# Generated by Django 5.2 on 2025-04-30 13:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccess', '0030_alter_unit_unit_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='useraccess.course'),
        ),
    ]
