# Generated by Django 5.2 on 2025-04-30 13:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccess', '0031_alter_unit_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentapp',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='useraccess.course'),
        ),
    ]
