# Generated by Django 5.2 on 2025-04-30 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccess', '0032_alter_studentapp_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='created_by',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='unit',
            name='name',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='unit',
            name='teacher',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
